name: MyEdda
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74404
title: My Dreams My Belief My Edda
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bc9073'
    - '#221b14'
    - '#4c3a2f'
    - '#9d7860'
  brandStrength: 1
  lightness: 0.6426149639301002
  saturation: 0.5
  rhythmicContrast: 0.2708224512171
purpose: []
